version: "3.9"
services:
  clickhouse111:
    image: clickhouse/clickhouse-server:latest
    hostname: clickhouse111
    container_name: clickhouse111
    ports:
      - 9111:9000
      - 8114:8123
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      my-network:
        ipv4_address: 172.50.0.11
    volumes:
      - ./listen_host.xml:/etc/clickhouse-server/config.d/listen_host.xml 
networks:
  my-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.50.0.0/16
